### ISSUE TITLE
AttributeError: 'KubernetesInfrastructure' object has no attribute 'agentRunCommand'

### ISSUE THREAD

**Issue by opusmagnum** [bitmovin/bitmovin-python#13]
Hi,

as I run a `pull_infrastructure_status.py` script, I got:
```
>python3 pull_infrastructure_status.py                                                                                                                                                             
2017-04-03 15:53:30,593 bitmovin.rest.http_client.BitmovinHttpClient INFO     REQUEST: GET encoding/infrastructure/kubernetes/XXXXXXXXXXX
<bitmovin.resources.models.infrastructures.kubernetes_infrastructure.KubernetesInfrastructure object at 0x10f472c88>

2017-04-03 15:53:30.885455
╒══════════════════════════╤══════════╤═════════════╕
│ Name                     │ Online   │ Connected   │
╞══════════════════════════╪══════════╪═════════════╡
│ XXXXXXXXXXXXXXXXXXXXXXXX │ True     │ True        │
╘══════════════════════════╧══════════╧═════════════╛
Traceback (most recent call last):
  File "pull_infrastructure_status.py", line 54, in <module>
    main(sys.argv[1:])
  File "pull_infrastructure_status.py", line 48, in main
    print('\nAgent run command:\n------------------\n{}\n'.format(k8s.agentRunCommand))
AttributeError: 'KubernetesInfrastructure' object has no attribute 'agentRunCommand'
```

Should not it be -- `k8s.agentDeploymentDownloadUrl` instead of `agentRunCommand`?

**Comment by rkersche** [comment]
Thanks for reporting this. This is now corrected in the latest master merge:
https://github.com/bitmovin/bitmovin-python/blob/master/examples/encoding/infrastructure/pull_infrastructure_status.py
